---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: rabbit
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: teams
    # TODO: we're temporarily supporting dependency on an existing default storage class
    # on the cluster, this hack will trigger re-queue on Addons until one exists
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.1-1"
    appversion.kubeaddons.mesosphere.io/rabbit: "1.0.1"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  chartReference:
    chart: rabbitmq
    repo: http://myhelmrepo:8080/
    values: |
      replicas: 2
      rabbitmq:
        ## RabbitMQ application username
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        username: user
      
        ## RabbitMQ application password
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        # password:
        # existingPasswordSecret: name-of-existing-secret
      
        ## Erlang cookie to determine whether different nodes are allowed to communicate with each other
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        # erlangCookie:
        # existingErlangSecret: name-of-existing-secret
      
        ## Node name to cluster with. e.g.: `clusternode@hostname`
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        # rabbitmqClusterNodeName:
      
        ## Value for the RABBITMQ_LOGS environment variable
        ## ref: https://www.rabbitmq.com/logging.html#log-file-location
        ##
        logs: '-'
      
        ## RabbitMQ Max File Descriptors
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ## ref: https://www.rabbitmq.com/install-debian.html#kernel-resource-limits
        ##
        setUlimitNofiles: true
        ulimitNofiles: '65536'
      
        ## RabbitMQ maximum available scheduler threads and online scheduler threads
        ## ref: https://hamidreza-s.github.io/erlang/scheduling/real-time/preemptive/migration/2016/02/09/erlang-scheduler-details.html#scheduler-threads
        ##
        maxAvailableSchedulers: 2
        onlineSchedulers: 1
      
        ## Plugins to enable
        plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s"
      
        ## Extra plugins to enable
        ## Use this instead of `plugins` to add new plugins
        extraPlugins: "rabbitmq_auth_backend_ldap"
      
        ## Clustering settings
        clustering:
          address_type: hostname
          k8s_domain: cluster.local
          ## Rebalance master for queues in cluster when new replica is created
          ## ref: https://www.rabbitmq.com/rabbitmq-queues.8.html#rebalance
          rebalance: false
      
        loadDefinition:
          enabled: false
          secretName: load-definition
      
        ## environment variables to configure rabbitmq
        ## ref: https://www.rabbitmq.com/configure.html#customise-environment
        env: {}
      
        ## Configuration file content: required cluster configuration
        ## Do not override unless you know what you are doing. To add more configuration, use `extraConfiguration` of `advancedConfiguration` instead
        configuration: |-
          ## Clustering
          cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
          cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
          cluster_formation.node_cleanup.interval = 10
          cluster_formation.node_cleanup.only_log_warning = true
          cluster_partition_handling = autoheal
          # queue master locator
          queue_master_locator=min-masters
          # enable guest user
          loopback_users.guest = false
        ## Configuration file content: extra configuration
        ## Use this instead of `configuration` to add more configuration
        extraConfiguration: |-
          #disk_free_limit.absolute = 50MB
          #management.load_definitions = /app/load_definition.json
    version: 8.7.0
