---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: rabbit
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: teams
    # TODO: we're temporarily supporting dependency on an existing default storage class
    # on the cluster, this hack will trigger re-queue on Addons until one exists
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.1-1"
    appversion.kubeaddons.mesosphere.io/rabbit: "1.0.1"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  chartReference:
    chart: rabbitmq
    repo: http://myhelmrepo:8080/
    values: |
      replicaCount: 1
      auth:
        ## RabbitMQ application username
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        username: user
      
        ## RabbitMQ application password
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        # password:
        # existingPasswordSecret: name-of-existing-secret
      
        ## Erlang cookie to determine whether different nodes are allowed to communicate with each other
        ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
        ##
        # erlangCookie:
        # existingErlangSecret: name-of-existing-secret

    version: 8.7.0
